### ISSUE TITLE
How convert nuimages to yolo in case of train?

### ISSUE THREAD

**Issue by ansl02** [YksinYoung/Nuscenes_images_to_yolo#2]
Thank for your sharing code.

How convert nuimages to yolo in case of train?

I tried changing the variables, but I'm not sure.

Please help me....

**Comment by YksinYoung** [comment]
Hi. Would you please provide the error ?

**Comment by ansl02** [comment]
Hi. I am trying 2 things.

The first thing is to set the file path to where I want to go and change the format of the mini.
File path: data-sets-nuimages-mini-(samples, sweeps, v1.0-mini, yolo)
Code: python nuscenes_to_yolo.py --nu-root ./data/sets/nuimages/mini/ --yl-root ./data/sets/mini/yolo/ --data-version v1.0-mini --data-type train

The first error message is as follows.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/ansl/anaconda3/envs/format/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "nuscenes_to_yolo.py", line 104, in run
    self.process()
  File "nuscenes_to_yolo.py", line 85, in process
    shutil.copy(dataset_root+item['filename'], yolo_images+stamp+'.jpg')
  File "/home/ansl/anaconda3/envs/format/lib/python3.7/shutil.py", line 248, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/home/ansl/anaconda3/envs/format/lib/python3.7/shutil.py", line 121, in copyfile
    with open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: './data/sets/mini/yolo/images/train/1533278795447155.jpg'
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/home/ansl/anaconda3/envs/format/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "nuscenes_to_yolo.py", line 104, in run
    self.process()
  File "nuscenes_to_yolo.py", line 85, in process
    shutil.copy(dataset_root+item['filename'], yolo_images+stamp+'.jpg')
  File "/home/ansl/anaconda3/envs/format/lib/python3.7/shutil.py", line 248, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/home/ansl/anaconda3/envs/format/lib/python3.7/shutil.py", line 121, in copyfile
    with open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: './data/sets/mini/yolo/images/train/1530672741162515.jpg'

Should I only set the file path to data/sets/nuimages/?
When the file path contained (samples, sweeps, v1.0-mini, yolo) files in /data/sets/nuimages/, it ran well.

Second, I want to do v1.0-train.
I only needed the front camera, so I downloaded only the front camera of sweep. When I ran the code below, it said that there was no left_camera image.
Do I need to download the sample instead of sweep?

Thank you.

**Comment by ansl02** [comment]
I was finally able to fix it.

Thanks for sharing your code.

Have a good day.
